アカウント登録
@startuml
actor 農家
boundary メニュー画面
boundary ログイン画面
boundary 新規登録選択画面
boundary 農家新規登録画面
control アカウント登録
entity ユーザーDB
boundary 完了画面

activate 農家
農家 -> メニュー画面:1:ログインまたは新規登録ボタンを押下する
activate メニュー画面
メニュー画面 -> ログイン画面:1.1:表示()
deactivate メニュー画面
activate ログイン画面

農家 -> ログイン画面:2:新規登録はこちらからを押下する
ログイン画面 -> 新規登録選択画面:2.1:表示()
deactivate ログイン画面
activate 新規登録選択画面


農家 -> 新規登録選択画面:3:農家を選択する
新規登録選択画面 -> 農家新規登録画面:3:表示()
deactivate 新規登録選択画面
activate 農家新規登録画面


農家 -> 農家新規登録画面:4:登録事項を入力する
農家新規登録画面 -> アカウント登録:4.1:起動()
activate アカウント登録

alt 完了時
アカウント登録 -> ユーザーDB:4.2:登録()
activate ユーザーDB
ユーザーDB --> アカウント登録
deactivate ユーザーDB
アカウント登録 -> 完了画面:4.3:表示()
activate 完了画面
deactivate 完了画面 

else 未入力または未登録の場合
アカウント登録 -> 農家新規登録画面:4.4:「未入力または未登録のものがありました」を表示()

else 住所使用不可の場合
アカウント登録 -> 農家新規登録画面:4.5:「この住所は使用できません」と表示()

else メールアドレス使用不可の場合
アカウント登録 -> 農家新規登録画面:4.6:「メールアドレスがすでに登録されています」と表示()
deactivate アカウント登録
deactivate 農家新規登録画面

end







@enduml