プロフィール編集
@startuml
actor 農家
boundary メニュー画面
control プロフィール編集画面表示
entity ユーザーDB
boundary プロフィール編集画面
control 表示
boundary 編集完了画面

activate 農家
農家 -> メニュー画面:1:プロフィール編集ボタンを押下する。
activate メニュー画面
メニュー画面 -> プロフィール編集画面表示:1.1:起動()
deactivate メニュー画面
activate プロフィール編集画面表示
プロフィール編集画面表示 -> ユーザーDB:1.2:プロフィール情報を取得()
activate ユーザーDB
ユーザーDB --> プロフィール編集画面表示
プロフィール編集画面表示 -> プロフィール編集画面:1.3:表示()
deactivate プロフィール編集画面表示
activate プロフィール編集画面

農家 -> プロフィール編集画面:2:表示される名前、プロフィール画像、説明欄 を入力してボタンを押下する
プロフィール編集画面 -> 表示:2.1:起動()
activate 表示

alt 完了時
表示 -> ユーザーDB:2.2:情報を保存()
ユーザーDB --> 表示
deactivate ユーザーDB
表示 -> 編集完了画面:2.3:「編集が完了しました」と表示()
activate 編集完了画面
deactivate 編集完了画面

else ユーザーネームが未入力の場合
表示 -> プロフィール編集画面:2.4:「ユーザーネームが未入力です」と表示()

else 説明欄が未入力の場合
表示-> プロフィール編集画面:2.5:「説明欄が未入力です」と表示()
deactivate 表示
deactivate プロフィール編集画面
end

@enduml