@startuml
actor システム管理者
boundary メニュー画面
control ユーザー情報
boundary ユーザー一覧画面
boundary 削除確認画面
control 確認処理
control 削除処理
entity ユーザーDB
boundary 削除完了画面

activate システム管理者
システム管理者 -> メニュー画面:1:ユーザー一覧画面を押下
activate メニュー画面
メニュー画面 -> ユーザー情報:1.1:確認()
activate ユーザー情報
deactivate メニュー画面
ユーザー情報 -> ユーザーDB:1.2:情報取得()
activate ユーザーDB
ユーザーDB --> ユーザー情報 :
ユーザー情報 -> ユーザー一覧画面:1.3:ユーザー一覧を表示()
activate ユーザー一覧画面
deactivate ユーザー情報

システム管理者 -> ユーザー一覧画面:2:削除ボタンを押下
ユーザー一覧画面 -> 削除確認画面:2.1:表示()
activate 削除確認画面
システム管理者 -> 削除確認画面:3:「はい」か「いいえ」を選択して押下
削除確認画面 -> 確認処理:3.1:確認()
activate 確認処理
deactivate 削除確認画面
alt 「はい」を選択した場合
    確認処理 -> 削除処理:3.2:削除処理()
    activate 削除処理
    削除処理 -> ユーザーDB:3.3:ユーザー削除()
    ユーザーDB --> 削除処理:
    deactivate ユーザーDB
    削除処理 -> 削除完了画面:3.4:表示()
    activate 削除完了画面
else 「いいえ」を選択した場合
    確認処理 --> ユーザー一覧画面:3.2.1:表示()
end


@enduml