@startuml

actor 購入者
boundary メニュー画面
control 商品情報
entity 商品DB
boundary カートの中身表示画面
boundary "カートの中身表示画面（空）"
boundary 支払方法選択画面
control 購入通知を送信
boundary 購入完了画面

activate 購入者
購入者 -> メニュー画面:1:カートボタンを押下する
activate メニュー画面
メニュー画面 -> 商品情報:1.1:表示()
deactivate メニュー画面
activate 商品情報
商品情報 -> 商品DB:1.2:商品情報を取得()
activate 商品DB
商品DB --> 商品情報:
deactivate 商品DB
alt 完了時
商品情報 -> カートの中身表示画面:1.3:表示()
activate カートの中身表示画面
else カートの中身が空の場合
    商品情報 -> "カートの中身表示画面（空）" :1.3.1:「カートの中身はありません」表示()
    activate "カートの中身表示画面（空）"
    deactivate "カートの中身表示画面（空）"
end
deactivate 商品情報
購入者 -> カートの中身表示画面:2:購入するボタンを押下する
カートの中身表示画面 -> 支払方法選択画面:2.1:支払情報を入力し完了ボタンを押下する
activate 支払方法選択画面
deactivate カートの中身表示画面
支払方法選択画面 -> 購入通知を送信:2.2:送信()
activate 購入通知を送信
alt 正常時
    購入通知を送信 -> 購入完了画面:2.3:表示()
    activate 購入完了画面
else 支払情報が誤りだった場合
    購入通知を送信 --> 支払方法選択画面:2.3.1:「この支払情報は正しくありません」表示()
end

@enduml