# Generated by Django 5.2.7 on 2025-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farm', 'Farm'), ('eat', 'Eat')], default='eat', max_length=10),
        ),
    ]
