# Generated by Django 5.2.7 on 2025-11-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farm', 'Farm'), ('eat', 'Eat')], max_length=10, null=True),
        ),
    ]
