# Generated by Django 5.2.7 on 2025-11-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
