# Generated by Django 5.2.7 on 2025-11-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Sale',
        ),
    ]
