# Generated by Django 5.2.7 on 2025-11-17 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_customuser_role_alter_item_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='farmerrating',
            unique_together={('user', 'farmer')},
        ),
    ]
