# Generated by Django 5.2.7 on 2025-11-18 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_farmerrating_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='judge/')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('approved', '承認'), ('rejected', '不許可'), ('resubmit', '再提出待ち')], default='pending', max_length=20)),
                ('resubmit_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
