# Generated by Django 5.2.7 on 2025-11-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_farmjudge'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmjudge',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmjudge',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='judge/'),
        ),
    ]
