# Generated by Django 5.2.7 on 2025-11-18 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_farmjudge_reason_alter_farmjudge_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
