# Generated by Django 5.2.7 on 2025-11-19 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_sale_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmjudge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge', to=settings.AUTH_USER_MODEL),
        ),
    ]
