出品管理閲覧
@startuml
actor 農家
boundary メニュー画面
control 出品管理画面表示
entity 商品DB
boundary 出品管理閲覧画面



activate 農家
農家 -> メニュー画面:1:出品管理ボタンを押下する
activate メニュー画面
メニュー画面 -> 出品管理画面表示:1.1:起動()
deactivate メニュー画面
activate 出品管理画面表示

出品管理画面表示 -> 商品DB:1.2:出品情報を取得()
activate 商品DB
商品DB --> 出品管理画面表示
deactivate 商品DB

alt 完了時
出品管理画面表示 -> 出品管理閲覧画面:1.3:表示()
activate 出品管理閲覧画面

else 商品が出品されていない場合
出品管理画面表示 -> 出品管理閲覧画面:1.4:「商品が出品されていません」と表示()
deactivate 出品管理画面表示
deactivate 出品管理閲覧画面
end


@enduml