@startuml

actor 購入者
boundary メニュー画面
control ログイン
boundary ログイン画面
boundary 新規登録選択画面
boundary 購入者新規登録画面
control アカウント登録
entity ユーザーDB
boundary 完了画面

activate 購入者
購入者 -> メニュー画面:1:ログインまたは新規登録画面をクリックする
activate メニュー画面
メニュー画面 -> ログイン画面:1.1:表示()
deactivate メニュー画面
activate ログイン画面
購入者 -> ログイン画面 : 2:新規登録はこちらボタンを押下する
ログイン画面 -> 新規登録選択画面:2.1:表示()
deactivate ログイン画面
activate 新規登録選択画面
購入者 -> 新規登録選択画面:3:飲食店向けボタンを押下する
新規登録選択画面 -> 購入者新規登録画面:3.2:表示()
deactivate 新規登録選択画面
activate 購入者新規登録画面
購入者 -> 購入者新規登録画面:4:必要事項を入力する
購入者新規登録画面 -> アカウント登録 : 4.1:登録()
activate アカウント登録
アカウント登録 -> ユーザーDB : 4.2:登録情報を保存()
activate ユーザーDB
ユーザーDB --> アカウント登録 :
deactivate ユーザーDB

alt 正常時
    アカウント登録 -> 完了画面:4.3表示()
    activate 完了画面
    deactivate 完了画面
else 入力情報が誤りだった場合
    アカウント登録 --> 購入者新規登録画面 : 4.3.1:「入力情報が誤りです」を表示()
else 住所が八王子ではない場合
    アカウント登録 -> 購入者新規登録画面 : 4.3.2:「この住所は使用できません」を表示()
else メールアドレスが既に登録されている場合
    アカウント登録 -> 購入者新規登録画面 : 4..3:「このメールアドレスはすでに登録されています」を表示()
deactivate アカウント登録
deactivate 購入者新規登録画面
end


@enduml