@startuml

actor 購入者
boundary メニュー画面
boundary ログアウト画面
control ログアウト
boundary ログアウト完了画面

activate 購入者
購入者 -> メニュー画面:1:ログアウトを押下する
activate メニュー画面
メニュー画面 -> ログアウト画面:1.1:表示()
activate ログアウト画面
購入者 -> ログアウト画面:2:「はい」または「いいえ」を押下する
ログアウト画面 -> ログアウト:2.1:ログアウト処理()
activate ログアウト
deactivate ログアウト画面
alt 「はい」を押下
    ログアウト -> ログアウト完了画面:2.1:表示()
    activate ログアウト完了画面
    deactivate ログアウト完了画面
else 「いいえ」を押下
    ログアウト --> メニュー画面:2.1.2:表示()
deactivate メニュー画面
deactivate ログアウト

end
@enduml