@startuml

actor 購入者
boundary メニュー画面
control 購入情報
entity 購入DB
boundary 購入履歴閲覧画面

activate 購入者
購入者 -> メニュー画面 :1:購入履歴閲覧を押下する
activate メニュー画面
メニュー画面 -> 購入情報:1.1:購入情報を取得()
deactivate メニュー画面
activate 購入情報
購入情報 -> 購入DB:1.2:購入情報を取得()
activate 購入DB
購入DB --> 購入情報:
deactivate 購入DB
alt 正常時
    購入情報 -> 購入履歴閲覧画面:1.3:表示()
    activate 購入履歴閲覧画面
else 購入していた商品がなかった場合
    購入情報 -> 購入履歴閲覧画面:1.3.1:「購入している商品がありません」と表示()
end
deactivate 購入情報
購入者 -> 購入履歴閲覧画面:2:閲覧

@enduml