@startuml

actor 購入者
boundary 商品画面
control ユーザー情報
entity ユーザーDB
boundary アカウントの詳細画面
boundary レビュー画面
control 処理確認
boundary レビュー完了画面

activate 購入者
購入者 -> 商品画面:1:アカウントを閲覧するボタンを押下する
activate 商品画面
商品画面 -> ユーザー情報:1.1:表示()
deactivate  商品画面
activate ユーザー情報
ユーザー情報 -> ユーザーDB:1.2:ユーザー情報を取得()
activate ユーザーDB
ユーザーDB --> ユーザー情報:
deactivate ユーザーDB
ユーザー情報 -> アカウントの詳細画面:1.3:表示()
activate アカウントの詳細画面
deactivate ユーザー情報

購入者 -> アカウントの詳細画面:2:アカウントを評価するボタンを押下する
アカウントの詳細画面 -> レビュー画面:2.1:星を付け、理由をつけて完了ボタンを押す
activate レビュー画面
alt 正常時
    レビュー画面 -> 処理確認:2.2:確認()
    activate 処理確認
    処理確認 -> レビュー完了画面:2.3:完了()
    activate レビュー完了画面
else 星がつけられてなかった場合
    処理確認 --> レビュー画面:2.3.1:「評価がつけられていません」を表示()
end

